### ISSUE TITLE
Error when plotting the VaR backtest

### ISSUE THREAD

**Issue by barty5260** [ibaris/VaR#5]
Hi, 

First of all, thank you very much for the project. The historic, parametric and monte carlo results seem consistent with mine. However, there is a problem when plotting a VaR backtest, could this be looked into? 

`AttributeError: 'VaR' object has no attribute 'plot'`

Thank you very much.

**Comment by barty5260** [comment]
After taking a deeper look. It seems that the Readme just has to be updated to use the new functions for the plots. Those being var_plot and cvar_plot.

**Comment by ibaris** [comment]
Thank you for bringing that matter to my attention. I sincerely apologize for the delay in my response. It appears that I did not receive any notification regarding your previous post, which is quite unusual. I will update te readme file this week 🤗

**Comment by ibaris** [comment]
Thank you so much @barty5260! I merged your pull request. I am glad to hear that you find this repository useful. Your support and collaboration are greatly appreciated.
