### ISSUE TITLE
Problems with var.backtest(method='p')

### ISSUE THREAD

**Issue by barty5260** [ibaris/VaR#8]
Hi @ibaris, I hope you are doing great.

I wanted to report some problems when accesing the parametric .backtest method. It appear that a `df = df.dropna()` code in backtest() is deleting quite a lot of data from the dfs. 

Below I have attached the var_plot (all plots are affected afaik). The data used is the one loaded from load_data() so it should be easy for you to replicate this.

![image](https://github.com/ibaris/VaR/assets/62222839/fad78c1b-0061-42ec-afff-19c8e7add664)

The conflicting code is, I believe, this:
![image](https://github.com/ibaris/VaR/assets/62222839/7bd4e1a6-d2d5-49af-9377-80ceaf4eb3b3)

It can be fixed by implementing a shifted .fillna. But I don't think this is the best of solutions.

**Comment by ibaris** [comment]
Thank you very much for the issue and your efforts to debug it. I will try to solve this issue in the weekend.

**Comment by barty5260** [comment]
No problem! You are welcome, in any case, thank you for sharing the repo! I am quite busy atm. But I think I will be able to help you eventually 😀

**Comment by ibaris** [comment]
Could you please check out [the branch](https://github.com/ibaris/VaR/tree/2023.6.3) and see if this issue is resolved for you as well?

**Comment by barty5260** [comment]
Yep. I believe it works as intended. Thanks a ton!
